# Day4_0: NumPy 핵심만 (Array & Vectorization) - 정답

## 📚 학습 목표

**Part 1: 기초**
1. NumPy 배열의 개념과 Python 리스트와의 차이 이해하기
2. 배열 생성 및 기본 인덱싱/슬라이싱 익히기
3. 배열의 형태(shape)와 차원(dimension) 다루기
4. 기본 배열 연산 수행하기
5. NumPy의 유용한 함수들 활용하기

**Part 2: 심화**
1. 브로드캐스팅(Broadcasting) 개념 완전 정복하기
2. 벡터화 연산의 성능 이점 체감하기
3. 배열 재구조화 및 결합 마스터하기
4. pandas 내부에서 NumPy가 작동하는 원리 이해하기

---

## 🎯 실습 퀴즈 정답

---

In [3]:
import numpy as np
import time

### Q1. 배열 생성 기초 ⭐

**문제**: 0부터 20까지 5씩 증가하는 NumPy 배열을 생성하세요.

In [11]:
result = np.arange(0,21,5)
print(result)
type(result)


[ 0  5 10 15 20]


numpy.ndarray

In [ ]:
# Q1 정답

# np.arange(시작, 끝, 간격) 사용
result = np.arange(0, 21, 5)  # 21은 미포함이므로 20까지 생성
print(result)

In [ ]:
# 테스트
assert len(result) == 5, "배열 길이가 5가 아닙니다"
assert result[0] == 0, "첫 번째 값이 0이 아닙니다"
assert result[-1] == 20, "마지막 값이 20이 아닙니다"
assert np.all(np.diff(result) == 5), "간격이 5가 아닙니다"
print("✅ 테스트 통과!")

### 💡 풀이 설명

**접근 방법**:
- `np.arange(start, stop, step)` 함수 사용
- `stop` 값은 포함되지 않으므로 21을 입력하여 20까지 포함

**핵심 개념**:
- `np.arange()`: Python의 `range()`와 유사하지만 NumPy 배열 반환
- 실수 간격도 가능 (예: `np.arange(0, 1, 0.1)`)

**대안 솔루션**:
```python
# 방법 2: 리스트 변환
result = np.array([0, 5, 10, 15, 20])

# 방법 3: linspace 사용
result = np.linspace(0, 20, 5)  # 0부터 20까지 5개로 균등 분할
```

**흔한 실수**:
- ❌ `np.arange(0, 20, 5)` → 마지막 20이 빠짐
- ❌ `np.arange(20, 5)` → step 누락 시 기본값 1 사용

**실무 팁**:
날짜/시간 간격, 가격대 구간 설정 시 자주 사용

---

### Q2. 배열 필터링 ⭐⭐

**문제**: 다음 매출 배열에서 150 이상인 값만 추출하세요.

In [12]:
sales = np.array([120, 180, 140, 200, 130, 170, 150])

result = sales[sales >= 150]
print(result)

[180 200 170 150]


In [ ]:
# Q2 정답

sales = np.array([120, 180, 140, 200, 130, 170, 150])

# 불린 인덱싱 사용
result = sales[sales >= 150]
print(result)

In [ ]:
# 테스트
assert len(result) == 4, "필터링 결과 개수가 4개가 아닙니다"
assert np.all(result >= 150), "150 미만 값이 포함되어 있습니다"
assert 180 in result and 200 in result, "180 또는 200이 누락되었습니다"
print("✅ 테스트 통과!")

### 💡 풀이 설명

**접근 방법**:
1. 조건식 `sales >= 150`으로 불린 배열 생성
2. 불린 배열을 인덱스로 사용하여 True인 요소만 추출

**핵심 개념**:
- **불린 인덱싱**: 조건을 만족하는 요소만 선택
- `sales >= 150` → `[False, True, False, True, ...]` 불린 배열 생성
- `sales[불린배열]` → True 위치의 값만 반환

**대안 솔루션**:
```python
# 방법 2: np.where 사용
indices = np.where(sales >= 150)[0]
result = sales[indices]

# 방법 3: 2단계로 분리
mask = sales >= 150
result = sales[mask]
```

**흔한 실수**:
- ❌ `sales[sales > 150]` → 150 제외 (문제에서는 '이상')
- ❌ 리스트 컴프리헨션 사용 → NumPy 장점 활용 못함

**실무 팁**:
pandas에서 `df[df['매출'] >= 150]` 동일한 방식으로 작동

---

### Q3. 벡터화 연산 ⭐⭐

**문제**: 상품 가격에 부가세 10%를 더한 최종 가격을 계산하세요.

In [13]:
prices = np.array([10000, 20000, 15000, 30000])
t_price = prices*(1.1)
print(t_price)

[11000. 22000. 16500. 33000.]


In [ ]:
a# Q3 정답

prices = np.array([10000, 20000, 15000, 30000])

# 벡터화 연산: 모든 요소에 동시 적용
final_prices = prices * 1.1  # 원가 * 1.1 = 원가 + 부가세 10%
print(final_prices)

In [ ]:
# 테스트
expected = np.array([11000., 22000., 16500., 33000.])
assert np.allclose(final_prices, expected), "계산 결과가 일치하지 않습니다"
assert final_prices[0] == 11000, "첫 번째 값이 11000이 아닙니다"
print("✅ 테스트 통과!")

### 💡 풀이 설명

**접근 방법**:
- 원가 + 부가세 10% = 원가 × 1.1
- NumPy 배열에 스칼라 곱셈 → 모든 요소에 자동 적용

**핵심 개념**:
- **벡터화 연산**: 반복문 없이 배열 전체에 연산 적용
- **브로드캐스팅**: 스칼라(1.1)가 배열 크기로 자동 확장

**대안 솔루션**:
```python
# 방법 2: 부가세 따로 계산
vat = prices * 0.1
final_prices = prices + vat

# 방법 3: 한 번에
final_prices = prices + prices * 0.1
```

**흔한 실수**:
- ❌ `prices * 0.1` → 부가세만 계산 (원가 빠짐)
- ❌ 반복문 사용 → 성능 저하
  ```python
  # 비효율적
  result = [p * 1.1 for p in prices]
  ```

**실무 팁**:
대용량 데이터(수백만 건) 처리 시 벡터화가 반복문보다 10~100배 빠름

---

### Q4. 집계 함수 활용 ⭐⭐

**문제**: 월별 매출의 평균, 최댓값, 최솟값을 각각 계산하세요.

In [14]:
monthly_sales = np.array([200, 250, 270, 300, 310, 320])
print(monthly_sales)

m_mean = monthly_sales.mean()
m_max = monthly_sales.max()
m_min = monthly_sales.min()
m_std = monthly_sales.std()
m_var = monthly_sales.var()

print(f"평균값: {m_mean}")
print(f"최대값: {m_max}")
print(f"최소값: {m_min}")

[200 250 270 300 310 320]
평균값: 275.0
최대값: 320
최소값: 200


In [ ]:
# Q4 정답

monthly_sales = np.array([1200, 1350, 1100, 1450, 1280, 1320])

# 각 통계량 계산
avg_sales = monthly_sales.mean()
max_sales = monthly_sales.max()
min_sales = monthly_sales.min()

print(f"평균: {avg_sales:.1f}만원")
print(f"최댓값: {max_sales}만원")
print(f"최솟값: {min_sales}만원")

In [ ]:
# 테스트
assert avg_sales == 1283.3333333333333, "평균 계산이 틀렸습니다"
assert max_sales == 1450, "최댓값이 틀렸습니다"
assert min_sales == 1100, "최솟값이 틀렸습니다"
print("✅ 테스트 통과!")

### 💡 풀이 설명

**접근 방법**:
NumPy 배열의 집계 메소드 직접 호출

**핵심 개념**:
- `.mean()`: 평균 (sum / count)
- `.max()`: 최댓값
- `.min()`: 최솟값
- 추가: `.sum()`, `.std()`, `.median()` 등

**대안 솔루션**:
```python
# 방법 2: np 모듈 함수 사용
avg_sales = np.mean(monthly_sales)
max_sales = np.max(monthly_sales)
min_sales = np.min(monthly_sales)

# 방법 3: Python 내장 함수 (느림)
avg_sales = sum(monthly_sales) / len(monthly_sales)
max_sales = max(monthly_sales)
```

**흔한 실수**:
- ❌ `monthly_sales.average()` → 메소드 이름 오류 (mean이 맞음)
- ❌ 2D 배열에서 axis 미지정 → 전체 평균 계산

**실무 팁**:
- `.argmax()`, `.argmin()`으로 최대/최소값의 인덱스 찾기
- pandas DataFrame에서도 동일하게 `.mean()`, `.max()` 사용

---

### Q5. 2차원 배열 인덱싱 ⭐⭐

**문제**: 다음 2차원 배열에서 두 번째 행(부산 지점)의 모든 값을 추출하세요.

In [17]:
branch_sales = np.array([
    [100, 200, 150],  # 서울 (index 0)
    [120, 180, 160],  # 부산 (index 1)
    [90, 210, 140]    # 대구 (index 2)
])

busan_sales = branch_sales[1]
print(busan_sales)

[120 180 160]


In [ ]:
# Q5 정답

branch_sales = np.array([
    [100, 200, 150],  # 서울 (index 0)
    [120, 180, 160],  # 부산 (index 1)
    [90, 210, 140]    # 대구 (index 2)
])

# 두 번째 행 (index 1) 추출
busan_sales = branch_sales[1]
print(busan_sales)

In [ ]:
# 테스트
expected = np.array([120, 180, 160])
assert np.array_equal(busan_sales, expected), "부산 지점 데이터가 틀렸습니다"
assert busan_sales.shape == (3,), "1차원 배열이어야 합니다"
print("✅ 테스트 통과!")

### 💡 풀이 설명

**접근 방법**:
- 2차원 배열에서 `arr[행]` 형태로 특정 행 전체 선택
- 인덱스는 0부터 시작하므로 두 번째 행 = index 1

**핵심 개념**:
- 2D 배열 인덱싱: `arr[행, 열]` 또는 `arr[행]` (전체 열)
- `branch_sales[1]` → 1번 행 전체 (3개 열 모두)
- `branch_sales[1, 2]` → 1번 행, 2번 열 (단일 값)

**대안 솔루션**:
```python
# 방법 2: 슬라이싱 사용
busan_sales = branch_sales[1, :]  # 명시적으로 모든 열 선택

# 방법 3: 특정 열만 선택
busan_product_A = branch_sales[1, 0]  # 부산 지점 상품 A만
```

**흔한 실수**:
- ❌ `branch_sales[2]` → 세 번째 행(대구) 선택
- ❌ `branch_sales[:, 1]` → 모든 지점의 두 번째 상품 (열 선택)

**실무 팁**:
- `axis=0`: 행 방향 연산, `axis=1`: 열 방향 연산
- pandas에서는 `df.iloc[1]` 또는 `df.loc['부산']` 사용

---

## Part 2 심화 퀴즈 정답

---

### Q6. 브로드캐스팅 활용 ⭐⭐⭐

**문제**: 각 지점별 판매량에 상품별 가격을 곱하여 지점별 매출을 계산하세요.

In [ ]:
quantity= np.arra

In [18]:
# Q6 정답

quantities = np.array([
    [10, 20, 15],  # 강남점
    [12, 18, 16]   # 분당점
])
prices = np.array([1000, 2000, 1500])  # 상품 A, B, C

# 브로드캐스팅: (2, 3) × (3,) → (2, 3)
revenue = quantities * prices

print("지점별 상품별 매출:")
print(revenue)
print("\n지점별 총 매출:", revenue.sum(axis=1))  # 각 행의 합

지점별 상품별 매출:
[[10000 40000 22500]
 [12000 36000 24000]]

지점별 총 매출: [72500 72000]


In [ ]:
# 테스트
expected = np.array([
    [10000, 40000, 22500],
    [12000, 36000, 24000]
])
assert np.array_equal(revenue, expected), "매출 계산이 틀렸습니다"
assert revenue.shape == (2, 3), "결과 형태가 (2, 3)이 아닙니다"
print("✅ 테스트 통과!")

### 💡 풀이 설명

**접근 방법**:
1. 2D 판매량 배열 (2, 3)과 1D 가격 배열 (3,) 곱셈
2. NumPy가 자동으로 가격 배열을 (2, 3)으로 확장 (브로드캐스팅)
3. 요소별 곱셈 수행

**핵심 개념**:
- **브로드캐스팅 규칙**: 차원이 다른 배열 연산 시 작은 배열을 자동 확장
- `prices` (3,) → [[1000, 2000, 1500], [1000, 2000, 1500]] (2, 3)로 확장
- 각 지점의 각 상품 판매량 × 해당 상품 가격

**대안 솔루션**:
```python
# 방법 2: 명시적 확장
prices_expanded = np.tile(prices, (2, 1))  # (3,) → (2, 3)
revenue = quantities * prices_expanded

# 방법 3: 반복문 (비효율적)
revenue = np.zeros_like(quantities)
for i in range(len(quantities)):
    revenue[i] = quantities[i] * prices
```

**흔한 실수**:
- ❌ 차원 불일치 에러 무시 → 수동으로 reshape 필요
- ❌ `quantities * prices.reshape(-1, 1)` → 잘못된 차원 변환

**실무 팁**:
pandas에서도 동일하게 작동: `df[['A', 'B', 'C']] * prices`

---

### Q7. 조건부 연산 (np.where) ⭐⭐⭐

**문제**: 매출이 150 이상이면 "목표달성", 아니면 "미달성" 레이블을 생성하세요.

In [ ]:
sales = np.array([120, 180, 140, 200, 130])

label = np.where(sales >=150, '목표달성', '미달성')
print(label)
u_label=np.unique(label)
print(u_label)




['미달성' '목표달성' '미달성' '목표달성' '미달성']
['목표달성' '미달성']


In [20]:
# Q7 정답

sales = np.array([120, 180, 140, 200, 130])

# np.where(조건, 참일때값, 거짓일때값)
labels = np.where(sales >= 150, "목표달성", "미달성")
print("매출:", sales)
print("레이블:", labels)

매출: [120 180 140 200 130]
레이블: ['미달성' '목표달성' '미달성' '목표달성' '미달성']


In [ ]:
# 테스트
expected = np.array(["미달성", "목표달성", "미달성", "목표달성", "미달성"])
assert np.array_equal(labels, expected), "레이블이 틀렸습니다"
assert labels[1] == "목표달성", "180은 목표달성이어야 합니다"
assert labels[0] == "미달성", "120은 미달성이어야 합니다"
print("✅ 테스트 통과!")

### 💡 풀이 설명

**접근 방법**:
`np.where()`를 사용하여 조건에 따라 다른 값 할당 (벡터화된 if-else)

**핵심 개념**:
- `np.where(조건, True값, False값)`
- 조건이 True인 위치 → "목표달성"
- 조건이 False인 위치 → "미달성"
- 반복문 없이 배열 전체에 조건부 로직 적용

**대안 솔루션**:
```python
# 방법 2: 리스트 컴프리헨션 (NumPy 장점 활용 못함)
labels = np.array(["목표달성" if s >= 150 else "미달성" for s in sales])

# 방법 3: 숫자로 먼저 변환 후 매핑
numeric_labels = np.where(sales >= 150, 1, 0)
labels = np.array(["목표달성" if x == 1 else "미달성" for x in numeric_labels])
```

**흔한 실수**:
- ❌ 조건식에 `and`, `or` 사용 → `&`, `|` 사용해야 함
- ❌ `np.where(sales >= 150)` → True 인덱스만 반환 (값 할당 아님)

**실무 팁**:
- 다중 조건: `np.select([조건1, 조건2], [값1, 값2], default=기본값)`
- pandas: `df['레이블'] = np.where(df['매출'] >= 150, ...)`

---

### Q8. 배열 재구조화 ⭐⭐⭐⭐

**문제**: 0부터 11까지의 배열을 3행 4열로 재구조화한 후, 각 행의 합계를 계산하세요.

In [ ]:
# Q8 정답

# 1. 0부터 11까지 배열 생성
arr = np.arange(12)
print("원본 배열:", arr)

# 2. 3행 4열로 재구조화
reshaped = arr.reshape(3, 4)
print("\n3x4 형태:")
print(reshaped)

# 3. 각 행의 합계 (axis=1)
row_sums = reshaped.sum(axis=1)
print("\n각 행의 합계:", row_sums)

In [ ]:
# 테스트
expected_sums = np.array([6, 22, 38])
assert np.array_equal(row_sums, expected_sums), "행 합계가 틀렸습니다"
assert reshaped.shape == (3, 4), "형태가 (3, 4)가 아닙니다"
assert row_sums[0] == 6, "첫 번째 행 합계가 6이 아닙니다"
print("✅ 테스트 통과!")

### 💡 풀이 설명

**접근 방법**:
1. `np.arange(12)`로 0~11 배열 생성
2. `.reshape(3, 4)`로 3행 4열로 변환
3. `.sum(axis=1)`로 행 방향(가로) 합계

**핵심 개념**:
- `.reshape(행, 열)`: 배열 형태 변경 (총 요소 수는 동일해야 함)
- `axis=0`: 열 방향(세로, ↓), `axis=1`: 행 방향(가로, →)
- 첫 번째 행: [0, 1, 2, 3] → 합계 6
- 두 번째 행: [4, 5, 6, 7] → 합계 22
- 세 번째 행: [8, 9, 10, 11] → 합계 38

**대안 솔루션**:
```python
# 방법 2: -1로 자동 계산
reshaped = arr.reshape(3, -1)  # 4가 자동 계산됨

# 방법 3: 열 합계 (axis=0)
col_sums = reshaped.sum(axis=0)  # [12, 15, 18, 21]
```

**흔한 실수**:
- ❌ `.reshape(3, 5)` → 총 15개 필요하지만 12개만 있음 (에러)
- ❌ `axis=0` 사용 → 열 합계 계산됨
- ❌ `.sum()` axis 미지정 → 전체 합계 (66)

**실무 팁**:
- pandas에서 `df.sum(axis=1)`: 각 행의 합 (행별 총계)
- pandas에서 `df.sum(axis=0)`: 각 열의 합 (열별 총계)

---

### Q9. 성능 비교 실험 ⭐⭐⭐⭐

**문제**: 10만 개 데이터에 대해 `(값 * 3 + 100) / 2` 연산을 수행할 때, Python 반복문과 NumPy 벡터화의 속도를 비교하세요.

In [ ]:
# Q9 정답

# 데이터 생성
data = np.random.randint(1, 100, size=100_000)

# 방법 1: Python 반복문
start = time.time()
result_loop = []
for d in data:
    result_loop.append((d * 3 + 100) / 2)
time_loop = time.time() - start

# 방법 2: NumPy 벡터화
start = time.time()
result_numpy = (data * 3 + 100) / 2
time_numpy = time.time() - start

# 결과 출력
print(f"반복문 시간: {time_loop:.6f}초")
print(f"벡터화 시간: {time_numpy:.6f}초")
print(f"\n성능 향상: {time_loop / time_numpy:.1f}배 빠름!")

In [ ]:
# 테스트
assert len(result_numpy) == 100_000, "결과 개수가 100,000개가 아닙니다"
assert time_numpy < time_loop, "NumPy가 더 느립니다 (이상)"
assert time_loop / time_numpy > 5, "성능 차이가 5배 이상이어야 정상"
print("✅ 테스트 통과!")

### 💡 풀이 설명

**접근 방법**:
1. 동일한 데이터로 두 가지 방법 실행
2. `time.time()`으로 시작/종료 시간 측정
3. 시간 차이 비교

**핵심 개념**:
- **벡터화의 성능 이점**: C/Fortran으로 구현된 내부 연산 사용
- Python 반복문: 각 요소마다 Python 인터프리터 호출
- NumPy 벡터화: 한 번의 호출로 전체 배열 처리
- 일반적으로 10~100배 성능 차이

**대안 솔루션**:
```python
# 방법 3: 리스트 컴프리헨션 (반복문보다 약간 빠름)
result_comp = [(d * 3 + 100) / 2 for d in data]

# 방법 4: map 함수
result_map = list(map(lambda d: (d * 3 + 100) / 2, data))
```

**흔한 실수**:
- ❌ 작은 데이터셋(100개)으로 테스트 → 차이 미미
- ❌ 반복 측정 안 함 → 시스템 노이즈 영향

**실무 팁**:
- 데이터 10만 건 이상: NumPy 필수
- pandas DataFrame 연산도 내부적으로 NumPy 사용
- 복잡한 로직은 `numba` 라이브러리로 JIT 컴파일

---

### Q10. 종합 문제 - 분기 실적 분석 ⭐⭐⭐⭐⭐

**문제**: 다음 분기 실적 데이터를 분석하세요.

**요구사항**:
1. 각 지점의 분기 총 매출 계산
2. 각 월의 전체 지점 합계 계산
3. 전체 평균 매출보다 높은 실적만 추출
4. 최고 실적 지점과 월 찾기

In [ ]:
# Q10 정답

quarterly_data = np.array([
    [1200, 1350, 1280],  # 강남점
    [980, 1050, 1120],   # 분당점
    [1100, 1200, 1150]   # 판교점
])

# 1. 각 지점의 분기 총 매출 (행별 합계)
branch_totals = quarterly_data.sum(axis=1)
print("1. 지점별 분기 총매출:")
print(f"   강남점: {branch_totals[0]:,}만원")
print(f"   분당점: {branch_totals[1]:,}만원")
print(f"   판교점: {branch_totals[2]:,}만원")

# 2. 각 월의 전체 지점 합계 (열별 합계)
monthly_totals = quarterly_data.sum(axis=0)
print("\n2. 월별 전체 매출:")
for i, total in enumerate(monthly_totals, 1):
    print(f"   {i}월: {total:,}만원")

# 3. 전체 평균보다 높은 실적만 추출
overall_avg = quarterly_data.mean()
above_avg = quarterly_data[quarterly_data > overall_avg]
print(f"\n3. 전체 평균: {overall_avg:.1f}만원")
print(f"   평균 이상 실적: {above_avg}")

# 4. 최고 실적 지점과 월 찾기
max_value = quarterly_data.max()
max_position = np.unravel_index(quarterly_data.argmax(), quarterly_data.shape)
branch_names = ["강남점", "분당점", "판교점"]
print(f"\n4. 최고 실적: {max_value}만원")
print(f"   지점: {branch_names[max_position[0]]}")
print(f"   월: {max_position[1] + 1}월")

In [ ]:
# 테스트
assert branch_totals[0] == 3830, "강남점 총매출이 틀렸습니다"
assert monthly_totals[1] == 3600, "2월 총매출이 틀렸습니다"
assert overall_avg == 1183.3333333333333, "전체 평균이 틀렸습니다"
assert max_value == 1350, "최댓값이 1350이 아닙니다"
assert max_position == (0, 1), "최고 실적 위치가 틀렸습니다"
print("✅ 테스트 통과!")

### 💡 풀이 설명

**접근 방법**:
1. `axis=1` (행별) vs `axis=0` (열별) 구분
2. 불린 인덱싱으로 조건 필터링
3. `argmax()`로 최댓값 인덱스 → `unravel_index()`로 2D 좌표 변환

**핵심 개념**:
- **axis 이해**: 
  - `axis=0` (↓): 각 열에 대해 연산 (지점 간 비교)
  - `axis=1` (→): 각 행에 대해 연산 (월별 비교)
- **argmax()**: 최댓값의 1D 인덱스 반환
- **unravel_index()**: 1D 인덱스 → 2D (행, 열) 변환

**대안 솔루션**:
```python
# 방법 2: 최댓값 위치 직접 찾기
for i in range(quarterly_data.shape[0]):
    for j in range(quarterly_data.shape[1]):
        if quarterly_data[i, j] == max_value:
            max_position = (i, j)

# 방법 3: where 사용
max_position = np.where(quarterly_data == max_value)
```

**흔한 실수**:
- ❌ `axis=0`과 `axis=1` 혼동
- ❌ `argmax()` 결과를 2D 인덱스로 직접 사용
- ❌ 월 번호를 0부터 출력 (1월 = index 0)

**실무 팁**:
- pandas에서 `df.sum(axis=1)`: 각 행의 합
- pandas에서 `df.idxmax()`: 최댓값의 인덱스(레이블) 반환
- 복잡한 분석은 pandas가 더 편리 (열 이름 활용)

---

## 📊 학습 정리

### Part 1: 기초 핵심 요약

| 개념 | 핵심 함수/메소드 | 실무 활용 |
|------|----------------|----------|
| 배열 생성 | `np.array()`, `np.arange()`, `np.zeros()`, `np.ones()` | 초기 데이터 구조화, 재고 초기화 |
| 인덱싱 | `arr[조건]`, `arr[start:end]` | 조건부 필터링, 기간별 추출 |
| 형태 | `.shape`, `.ndim`, `.reshape()` | 데이터 재구조화, 차원 변환 |
| 집계 | `.sum()`, `.mean()`, `.max()`, `.min()`, `.std()` | KPI 계산, 통계 요약 |

### Part 2: 심화 핵심 요약

| 기법 | 문법 | 언제 쓰나? |
|------|------|----------|
| 브로드캐스팅 | 크기 다른 배열끼리 자동 연산 | 지역별 할인율, 상품별 가격 적용 |
| 벡터화 | 반복문 없이 배열 전체 연산 | 대용량 데이터 고속 처리 |
| np.where | `np.where(조건, 참, 거짓)` | 조건부 값 할당 (if-else 대체) |
| vstack/hstack | 배열 수직/수평 결합 | 월별 데이터 통합, 분기 집계 |

### 💡 실무 팁

1. **pandas 전에 NumPy**: pandas DataFrame도 내부적으로 NumPy 배열 사용
2. **벡터화 우선**: 반복문 대신 NumPy 연산 사용 → 10~100배 빠름
3. **메모리 효율**: 같은 타입 데이터는 NumPy가 리스트보다 메모리 효율적
4. **브로드캐스팅 활용**: 반복문 없이 조건별 계산 가능
5. **axis 이해**: `axis=0` (행 방향), `axis=1` (열 방향) - 집계 시 필수
6. **pandas 연동**: `.values`로 NumPy 배열 추출 → 고속 연산 → DataFrame 재할당